# ifdef FYBA_STRINGS_EN
/* =========== ENGLISH FYBA_STRINGS  ================== */

#define FYBA_STRING_BASE_UNKNOWN_TYPE    L"Unknown base type, cannot open base."
#define FYBA_STRING_BASE_TOO_MANY_GROUPS L"Too many groups in base."
#define FYBA_STRING_FILE_NOT_FOUND       L"No .sos file found by the name:"
#define FYBA_STRING_BASE_FYBA_NOT_INITD  L"Cannot open base - FYBA has not been initialized."
#define FYBA_STRING_BASE_NOT_OPEN        L"Cannot open SOSI-file. Base has not been opened."
#define FYBA_STRING_FILE_PERM_DENIED     L"Permission denied opening SOSI-file or creating index folder."
#define FYBA_STRING_FILE_OPEN_FAILED     L"Error opening file:"
#define FYBA_STRING_FILE_OMRAADE_MISSING L"..OMRÅDE missing in file header:"
#define FYBA_STRING_FILE_MIN_NOE_MISSING L"...MIN-NØ missing in file header:"
#define FYBA_STRING_FILE_MAX_NOE_MISSING L"...MAX-NØ missing in file header:"
#define FYBA_STRING_BASE_INDEX_ABORTED   L"Index construction aborted."
#define FYBA_STRING_BASE_OPEN_FAILED     L"Error opening:"
#define FYBA_STRING_FILE_NEW_HEADER      L"New header in:"
#define FYBA_STRING_FILE_NOT_SOSI        L"Not a SOSI file:"
#define FYBA_STRING_FILE_OMRAADE_INVALID L"Invalid OMRÅDE in file header! (No dimensions.)"
#define FYBA_STRING_SAVE_INVALID_FILEPTR L"Invalid file pointer while saving."
#define FYBA_STRING_OPEN_BASE_IS_KLADDE  L"Cannot open SOSI file. Base was opened as KLADDE. This can only be combined with sequential reading/writing."
#define FYBA_STRING_FILE_READ_ERROR_HODE L"Reading error in header line."
#define FYBA_STRING_FILE_TRANSPAR_MISSING L"..TRANSPAR missing in file header."
#define FYBA_STRING_FILE_KOORDSYS_MISSING L"...KOORDSYS missing in file header."
#define FYBA_STRING_FILE_ORIGO_MISSING   L"...ORIGO-NØ missing in file header. (Check the encoding!)"
#define FYBA_STRING_FILE_ENHET_MISSING   L"...ENHET missing in file header."
#define FYBA_STRING_NAME_TABLE_FULL      L"Name table is full."
#define FYBA_STRING_INVALID_GROUP_NAME   L"Invalid group name:"
#define FYBA_STRING_FILE_NO_CURRENT_GROUP L"No current group - nothing read."
#define FYBA_STRING_OPEN_INVALID_EXTERN  L"Invalid external file - nothing read."
#define FYBA_STRING_SAVE_INVALID_EXTERN  L"Invalid external file - nothing written."
#define FYBA_STRING_SAVE_NO_WRITE_ACCESS L"No write access, nothing written to the file:"
#define FYBA_STRING_GROUP_DELETED        L"Group is deleted."
#define FYBA_STRING_FILE_INVALID_GROUP_NR L"Invalid group number, nothing read."
#define FYBA_STRING_NEW_INVALID_FILE     L"Invalid file, cannot create new group."
#define FYBA_STRING_NEW_NO_WRITE_ACCESS  L"No write access, cannot create new group."
#define FYBA_STRING_NEW_TOO_MANY_GROUPS  L"Too many groups in base, cannot create new group."
#define FYBA_STRING_NEW_INVALID_LINE_GI  L"Invalid line number for new GINFO"
#define FYBA_STRING_NEW_INVALID_LINE_COO L"Invalid line number for new coordinates."
#define FYBA_STRING_SLUTT_MISSING        L".SLUTT missing in SOSI file."
#define FYBA_STRING_READ_ERROR           L"Error reading SOSI file."
#define FYBA_STRING_GROUP_REFERRED_TO    L"Group is referenced by another group, cannot be deleted."
#define FYBA_STRING_INVALID_GI_LINE_1    L"Invalid GINFO line nr. 1."
#define FYBA_STRING_CANT_REMOVE_HEADER   L"You cannot remove the file header."
#define FYBA_STRING_NO_CURRENT_GROUP     L"No current group, nothing changed."
#define FYBA_STRING_DEL_UNKNOWN_FLAG     L"Group has an unknown NGIS change flag, cannot be removed."
#define FYBA_STRING_DEL_NO_WRITE_ACCESS  L"No write access, group cannot be removed."
#define FYBA_STRING_ERR_FILESIZE_CHANGE  L"Error changing file size."
#define FYBA_STRING_DISK_SOON_FULL       L"Your disk is soon full. Make some room at : "
#define FYBA_STRING_NOT_A_HEADER         L"Current group is not a file header - nothing changed."
#define FYBA_STRING_DEL_NOT_SEQUENTIAL   L"You cannot delete groups in sequential mode."
#define FYBA_STRING_NO_CHANGE_HEADERS    L"Cannot change KOORDSYS, ENHET, ORIGO or NGIS-LAG in a file with data."
#define FYBA_STRING_CANT_REWRITE_HEADER  L"No room to write back header."
#define FYBA_STRING_SAVE_NOT_A_HEADER    L"Group is not a header, cannot save it as such."
#define FYBA_STRING_CANT_COPY_COORD      L"Cannot copy coordinates from current group to another."
#define FYBA_STRING_CANT_COPY_COORD_ROOM L"Cannot copy coordinates: Not enough room in ring buffer."
#define FYBA_STRING_ENHET_NOT_SET        L"ENHET is set to 0.0 in the file header, or header is missing:"
#define FYBA_STRING_CANT_READ_FILE_SIZE  L"Error while retrieving file size:"
#define FYBA_STRING_PINFO_LONG_OR_NO_NOE L"PINFO too long -OR- ..NØ missing after PINFO:"
#define FYBA_STRING_LOGIC_FAIL           L"Logic error in SOSI-file\nLine order error, property among coordinates:\n"
#define FYBA_STRING_MAX_1_KP_OR_NO_NOE   L"Max. 1 KP per point -OR- ..NØ missing after KP:"
#define FYBA_STRING_NO_ROOM_IN_HEADER    L"No room in header or corrupt:"
#define FYBA_STRING_INVALID_GAP          L"Invalid gap in point-indentation:"
#define FYBA_STRING_TOO_MANY_COORDINATES L"Too many coordinates in group:"
#define FYBA_STRING_TOO_MANY_GINFO       L"GINFO-line lost.  Too many GINFO lines in:"
#define FYBA_STRING_TOO_MUCH_GINFO       L"GINFO-line lost.  Too much GINFO in:"
#define FYBA_STRING_TOO_MUCH_PINFO       L"PINFO lost. Too much PINFO in:"
#define FYBA_STRING_CANT_EXTEND_GROUP    L"Cannot extend group (too many coordinates):"
#define FYBA_STRING_READ_NO_WRITE_ACCESS L"Cannot read new group. No write access to save current, changed group. File:"
#define FYBA_STRING_READ_LINE_TOO_LONG   L"Cannot read SOSI file. Line too long: "
#define FYBA_STRING_INVALID_POINT        L"Invalid point number:"
#define FYBA_STRING_INVALID_GINFO        L"Invalid GINFO line number:"
#define FYBA_STRING_INVALID_NODE         L"Invalid Node type:"
#define FYBA_STRING_INVALID_GROUP_NAME   L"Invalid group name:"
#define FYBA_STRING_PINFO_TOO_LONG       L"PINFO too long, cannot fetch value. (Contact support/developers)"
#define FYBA_STRING_INVALID_REF          L"Invalid REF in file:"
#define FYBA_STRING_CANT_CHANGE_ENHET    L"Cannot change ENHET in a file with data:"
#define FYBA_STRING_CANT_CHANGE_NGIS_LAG L"Cannot change ..NGIS-LAG in a file with data:"
#define FYBA_STRING_INVALID_BUE          L"Invalid curve (BUE) in file:"
#define FYBA_STRING_INVALID_PRIKKNIVO    L"Invalid gap in point-indentation in file:"
#define FYBA_STRING_CANT_CHANGE_ORIGO_NOE L"Cannot change ..ORIGO-NØ in a file with data:"
#define FYBA_STRING_PROB_TOO_LONG_PINFO  L"PINFO (probably) too long."
#define FYBA_STRING_NO_HOEYDE_WITH_NAD   L"Group has ..NAD, cannot store height per point:"
#define FYBA_STRING_NO_HOEYDE_WITH_NAH   L"Group has ..NAH, cannot store depth per point: "
#define FYBA_STRING_LINE_TOO_LONG        L"SOSI-line too long (max. 1024 characters), line stripped. Group: "
#define FYBA_STRING_INVALID_SERIAL       L"Invalid serial number:"
#define FYBA_STRING_INVALID_LINE_NR      L"Invalid line number in table to unpack info:" /* check */
#define FYBA_STRING_INVALID_GROUP_NR     L"Invalid group number, identifier corrupt:"
#define FYBA_STRING_ERR_READING_BUFFER   L"Error reading from ring buffer."
#define FYBA_STRING_ERR_WRITING_BUFFER   L"Error writing to ring buffer."
#define FYBA_STRING_MUST_INIT_INDEX      L"Must initialize index table before saving."
#define FYBA_STRING_ERR_READING_SEARCHT  L"Error reading geographic search table."
#define FYBA_STRING_ERR_WRITING_SEARCHT  L"Error writing geographic search table."
#define FYBA_STRING_ERR_READING_GROUPT   L"Error reading group table."
#define FYBA_STRING_ERR_WRITING_GROUPT   L"Error writing group table."
#define FYBA_STRING_ERR_READING_SERIALT  L"Error reading serial number table."
#define FYBA_STRING_ERR_WRITING_SERIALT  L"Error writing serial number table."
#define FYBA_STRING_ERR_READING_INFOT    L"Error reading info table."
#define FYBA_STRING_ERR_WRITING_INFOT    L"Error writing info table."
#define FYBA_STRING_ERR_INFOT_FULL       L"Info storage table is full."
#define FYBA_STRING_ERR_READING_BRUKT    L"Error reading 'brukt'-table." /* check */
#define FYBA_STRING_ERR_WRITING_BRUKT    L"Error writing 'brukt'-table."
#define FYBA_STRING_NO_BLANKS_FILENAME   L"Cannot create catalog for index files with spaces in file name.\n"
#define FYBA_STRING_TOO_MANY_CHOICES     L"Too many selections, no room for:"
#define FYBA_STRING_MISPLACED_CHOICE     L"Misplaced selection line:"
#define FYBA_STRING_GROUP_CHOICE_MISSING L"Included group selection not found:"
#define FYBA_STRING_INVALID_CHOICE       L"Invalid selection line:"
#define FYBA_STRING_NO_COMPLEX_CHOICE    L"Complex selections (with OG or ELLER) do not work on PINFO."
#define FYBA_STRING_GAP_IN_LEVEL         L"Invalid gap in indentation:"
#define FYBA_STRING_TOO_MANY_PRIORITIES  L"Too many priorities, ignoring:"
#define FYBA_STRING_DUPLICATE_DEFINITION L"Level is defined twice in:" /* check */
#define FYBA_STRING_FILE_INVALID_TEGNSETT L"Invalid ..TEGNSETT in file header:"
#define FYBA_STRING_UNKNOWN_ERROR        L"Unknown error message. Nr.: %d"

# else 
/* =========== NORWEGIAN FYBA_STRINGS (DEFAULT) ======= */

#define FYBA_STRING_BASE_UNKNOWN_TYPE    L"Ukjent BaseType er gitt, kan derfor ikke åpne base!"
#define FYBA_STRING_BASE_TOO_MANY_GROUPS L"For mange grupper i basen:"
#define FYBA_STRING_FILE_NOT_FOUND       L"Finner ingen .SOS fil med navnet:"
#define FYBA_STRING_BASE_FYBA_NOT_INITD  L"Kan ikke åpne base, FYBA er ikke initiert!"
#define FYBA_STRING_BASE_NOT_OPEN        L"Kan ikke åpne SOSI-fil, fordi det ikke er åpnet noen base!"
#define FYBA_STRING_FILE_PERM_DENIED     L"Tillatelse nektet under åpning av SOSI-fil eller lagring av indeks."
#define FYBA_STRING_FILE_OPEN_FAILED     L"Åpningsfeil på filen:"
#define FYBA_STRING_FILE_OMRAADE_MISSING L"..OMRÅDE mangler i filhodet på filen:"
#define FYBA_STRING_FILE_MIN_NOE_MISSING L"...MIN-NØ mangler i filhodet på filen:"
#define FYBA_STRING_FILE_MAX_NOE_MISSING L"...MAX-NØ mangler i filhodet på filen:"
#define FYBA_STRING_BASE_INDEX_ABORTED   L"Indeksoppbygging er avbrutt!"
#define FYBA_STRING_BASE_OPEN_FAILED     L"Åpningsfeil på:"
#define FYBA_STRING_FILE_NEW_HEADER      L"Nytt hode på:"
#define FYBA_STRING_FILE_NOT_SOSI        L"Ikke SOSI-fil:"
#define FYBA_STRING_FILE_OMRAADE_INVALID L"Ulovlig OMRÅDE-angivelse i filhodet! (Ingen utstrekning.)"
#define FYBA_STRING_SAVE_INVALID_FILEPTR L"Ulovlig filpeker ved kall til lagringssystemet, rutine"
#define FYBA_STRING_OPEN_BASE_IS_KLADDE  L"Kan ikke åpne SOSI-fil. Basen er åpnet som kladdebase. Dette kan bare kombineres med sekvensiell les/skriv av SOSI-fil."
#define FYBA_STRING_FILE_READ_ERROR_HODE L"Lesefeil ved lesing av hodelinje."
#define FYBA_STRING_FILE_TRANSPAR_MISSING L"..TRANSPAR mangler i filhodet."
#define FYBA_STRING_FILE_KOORDSYS_MISSING L"...KOORDSYS mangler i filhodet."
#define FYBA_STRING_FILE_ORIGO_MISSING   L"...ORIGO-NØ mangler i filhodet. (Feil tegnsett?)"
#define FYBA_STRING_FILE_ENHET_MISSING   L"...ENHET mangler i filhodet."
#define FYBA_STRING_NAME_TABLE_FULL      L"Navnetabellen er full."
#define FYBA_STRING_INVALID_GROUP_NAME   L"Ulovlig gruppenavn:"
#define FYBA_STRING_FILE_NO_CURRENT_GROUP L"Ingen aktuell gruppe, ingenting er lest!"
#define FYBA_STRING_OPEN_INVALID_EXTERN  L"Ulovlig ekstern fil, ingenting er lest!"
#define FYBA_STRING_SAVE_INVALID_EXTERN  L"Ulovlig ekstern fil, ingenting er skrevet!"
#define FYBA_STRING_SAVE_NO_WRITE_ACCESS L"Du har ikke skriveaksess, ingenting er skrevet til filen:"
#define FYBA_STRING_GROUP_DELETED         L"Gruppen er sletta."
#define FYBA_STRING_FILE_INVALID_GROUP_NR L"Ulovlig gruppenummer, ingenting er lest!"
#define FYBA_STRING_NEW_INVALID_FILE     L"Ulovlig fil, kan ikke lage ny gruppe!"
#define FYBA_STRING_NEW_NO_WRITE_ACCESS  L"Du har ikke skriveaksess, kan ikke lage ny gruppe!"
#define FYBA_STRING_NEW_TOO_MANY_GROUPS  L"For mange grupper i basen, kan ikke lage ny gruppe:"
#define FYBA_STRING_NEW_INVALID_LINE_GI  L"Ulovlig linjenummer for ny GINFO:"
#define FYBA_STRING_NEW_INVALID_LINE_COO L"Ulovlig linjenummer for ny koordinat:"
#define FYBA_STRING_SLUTT_MISSING        L".SLUTT mangler på SOSI-filen"
#define FYBA_STRING_READ_ERROR           L"Lesefeil på SOSI-filen"
#define FYBA_STRING_GROUP_REFERRED_TO    L"Gruppen er referert fra annen gruppe, kan ikke slette gruppen!"
#define FYBA_STRING_INVALID_GI_LINE_1    L"Ulovlig GINFO-linje nr 1:"
#define FYBA_STRING_CANT_REMOVE_HEADER   L"Det er ikke mulig å slette filhodet!"
#define FYBA_STRING_NO_CURRENT_GROUP     L"Det er ingen aktuell gruppe, ingenting er utført!"
#define FYBA_STRING_DEL_UNKNOWN_FLAG     L"Gruppen har ukjent NGIS endringsflagg, kan ikke slette gruppen!"
#define FYBA_STRING_DEL_NO_WRITE_ACCESS  L"Du har ikke skriveaksess, kan ikke slette gruppen!"
#define FYBA_STRING_ERR_FILESIZE_CHANGE  L"Feil ved endring av filstørrelse!"
#define FYBA_STRING_DISK_SOON_FULL       L"Disken er snart full. Rydd plass til : "
#define FYBA_STRING_NOT_A_HEADER         L"Aktuell gruppe er ikke SOSI-filhode, ingenting er utført"
#define FYBA_STRING_DEL_NOT_SEQUENTIAL   L"Det er ikke mulig å slette gruppe på sekvensiell fil!"
#define FYBA_STRING_NO_CHANGE_HEADERS    L"Kan ikke endre KOORDSYS, ENHET, ORIGO eller NGIS-LAG på fil med data!"
#define FYBA_STRING_CANT_REWRITE_HEADER  L"Det er ikke plass til å skrive tilbake filhodet!"
#define FYBA_STRING_SAVE_NOT_A_HEADER    L"Gruppen er ikke filhode, kan ikke lagre den som filhode!"
#define FYBA_STRING_CANT_COPY_COORD      L"Kan ikke kopiere koord. fra akt. gruppe til akt.gruppe!"
#define FYBA_STRING_CANT_COPY_COORD_ROOM L"Kan ikke kopiere koordinater:  (ikke nok plass i ringbuffer)!"
#define FYBA_STRING_ENHET_NOT_SET        L"ENHET er 0.0 i filhodet, eller filhode mangler på filen:"
#define FYBA_STRING_CANT_READ_FILE_SIZE  L"Feil ved hent av filstørrelse på filen:"
#define FYBA_STRING_PINFO_LONG_OR_NO_NOE L"For lang PINFO / ..NØ mangler etter PINFO! :"
#define FYBA_STRING_LOGIC_FAIL           L"Logisk feil i SOSI-fil.\nNivåfeil, egenskap mellom koordinatene:\n"
#define FYBA_STRING_MAX_1_KP_OR_NO_NOE   L"Max. 1 KP pr. punkt / ..NØ mangler etter KP! :"
#define FYBA_STRING_NO_ROOM_IN_HEADER    L"Ikke plass til hodet, ødelagt på filen :"
#define FYBA_STRING_INVALID_GAP          L"Ulovlig sprang i prikk-nivå!:"
#define FYBA_STRING_TOO_MANY_COORDINATES L"For mange koordinater i gruppe:"
#define FYBA_STRING_TOO_MANY_GINFO       L"GINFO-linje mistes!  For mange GINFO linjer i:"
#define FYBA_STRING_TOO_MUCH_GINFO       L"GINFO-linje mistes!  For mye GINFO i:"
#define FYBA_STRING_TOO_MUCH_PINFO       L"PINFO mistes!  For mye PINFO i:"
#define FYBA_STRING_CANT_EXTEND_GROUP    L"Kan ikke utvide gruppe (for mange koordinater):"
#define FYBA_STRING_READ_NO_WRITE_ACCESS L"Kan ikke lese ny gruppe. Du har ikke skriveaksess for å lagre aktuell gruppe som er endret. Fil :"
#define FYBA_STRING_READ_LINE_TOO_LONG   L"Kan ikke lese SOSI-fil. For lang SOSI-linje: "
#define FYBA_STRING_INVALID_POINT        L"Ulovlig punktnummer:"
#define FYBA_STRING_INVALID_GINFO        L"Ulovlig GINFO-linje nummer:"
#define FYBA_STRING_INVALID_NODE         L"Ulovlig Knutepunkt-type:"
#define FYBA_STRING_INVALID_GROUP_NAME   L"Ulovlig gruppenavn:"
#define FYBA_STRING_PINFO_TOO_LONG       L"For lang PINFO, klarer ikke å hente verdi. (Kontakt FYSAK-support)"
#define FYBA_STRING_INVALID_REF          L"OBS! Ulovlig ref. i filen:"
#define FYBA_STRING_CANT_CHANGE_ENHET    L"Kan ikke endre ENHET på fil med data, bruker:"
#define FYBA_STRING_CANT_CHANGE_NGIS_LAG L"Kan ikke endre ..NGIS-LAG på fil med data, bruker:"
#define FYBA_STRING_INVALID_BUE          L"OBS! Ulovlig bue i filen:"
#define FYBA_STRING_INVALID_PRIKKNIVO    L"OBS! Ulovlig sprang i prikk-nivå i filen:"
#define FYBA_STRING_CANT_CHANGE_ORIGO_NOE L"Kan ikke endre ..ORIGO-NØ på fil med data, bruker:"
#define FYBA_STRING_PROB_TOO_LONG_PINFO  L"Sannsynligvis for lang PINFO !"
#define FYBA_STRING_NO_HOEYDE_WITH_NAD   L"Gruppen har ..NAD, kan ikke legge inn høyde på punktnivå i:"
#define FYBA_STRING_NO_HOEYDE_WITH_NAH   L"Gruppen har ..NAH, kan ikke legge inn dybde på punktnivå i: "
#define FYBA_STRING_LINE_TOO_LONG        L"For lang SOSI-linje (max 1024 tegn), linjen forkortes. Gruppe: "
#define FYBA_STRING_INVALID_SERIAL       L"Ulovlig serienummer:"
#define FYBA_STRING_INVALID_LINE_NR      L"Ulovlig linjenummer i tabell for upakka info:"
#define FYBA_STRING_INVALID_GROUP_NR     L"Ulovlig gruppenummer, merking fungerer ikke :"
#define FYBA_STRING_ERR_READING_BUFFER   L"Feil ved les fra ringbuffer!"
#define FYBA_STRING_ERR_WRITING_BUFFER   L"Feil ved skriv til ringbuffer!"
#define FYBA_STRING_MUST_INIT_INDEX      L"Indekstabellene må initieres før lagring"
#define FYBA_STRING_ERR_READING_SEARCHT  L"Feil ved les fra geografisk søketabell!"
#define FYBA_STRING_ERR_WRITING_SEARCHT  L"Feil ved skriv til geografisk søketabell!"
#define FYBA_STRING_ERR_READING_GROUPT   L"Feil ved les fra gruppetabell!"
#define FYBA_STRING_ERR_WRITING_GROUPT   L"Feil ved skriv til gruppetabell!"
#define FYBA_STRING_ERR_READING_SERIALT  L"Feil ved les fra serienummer-tabell!"
#define FYBA_STRING_ERR_WRITING_SERIALT  L"Feil ved skriv til serienummer-tabell!"
#define FYBA_STRING_ERR_READING_INFOT    L"Feil ved les fra info-tabell!"
#define FYBA_STRING_ERR_WRITING_INFOT    L"Feil ved skriv til info-tabell!"
#define FYBA_STRING_ERR_INFOT_FULL       L"Tabell for upakka info er full!"
#define FYBA_STRING_ERR_READING_BRUKT    L"Feil ved les fra brukt-tabell!"
#define FYBA_STRING_ERR_WRITING_BRUKT    L"Feil ved skriv til brukt-tabell!"
#define FYBA_STRING_NO_BLANKS_FILENAME   L"Kan ikke opprette katalog for indeksfiler når det er blanke sist i filnavnet!\n"
#define FYBA_STRING_TOO_MANY_CHOICES     L"For mange utvalg, ikke plass til:"
#define FYBA_STRING_MISPLACED_CHOICE     L"Feilplasert utvalgslinje:"
#define FYBA_STRING_GROUP_CHOICE_MISSING L"Inkludert gruppeuvtalg finnes ikke:"
#define FYBA_STRING_INVALID_CHOICE       L"Ulovlig utvalgslinje:"
#define FYBA_STRING_NO_COMPLEX_CHOICE    L"Komplekse utvalg (..OG og ..ELLER) fungerer ikke for PINFO!"
#define FYBA_STRING_GAP_IN_LEVEL         L"Ulovlig sprang i nivå!:"
#define FYBA_STRING_TOO_MANY_PRIORITIES  L"For mange prioriteter, mister prioritet :"
#define FYBA_STRING_DUPLICATE_DEFINITION L"Lag er dobbeltdefinert i utvalg :"
#define FYBA_STRING_FILE_INVALID_TEGNSETT L"Ulovlig ..TEGNSETT i filhode:"
#define FYBA_STRING_UNKNOWN_ERROR        L"Ukjent feilmelding. Nr.: %d"

# endif
